--INSERT INTO USERS(USER_NAME, LOGIN, EMAIL, BIRTHDAY) VALUES ('Test', 'Test login', 'test@email.ru', '1990-12-03');

INSERT INTO GENRES (GENRE_NAME) VALUES ('Комедия');
INSERT INTO GENRES (GENRE_NAME) VALUES ('Драма');
INSERT INTO GENRES (GENRE_NAME) VALUES ('Мультфильм');
INSERT INTO GENRES (GENRE_NAME) VALUES ('Триллер');
INSERT INTO GENRES (GENRE_NAME) VALUES ('Документальный');
INSERT INTO GENRES (GENRE_NAME) VALUES ('Боевик');

INSERT INTO RATINGS (RATING_NAME) VALUES ('G');
INSERT INTO RATINGS (RATING_NAME) VALUES ('PG');
INSERT INTO RATINGS (RATING_NAME) VALUES ('PG-13');
INSERT INTO RATINGS (RATING_NAME) VALUES ('R');
INSERT INTO RATINGS (RATING_NAME) VALUES ('NC-17');